### ISSUE TITLE
@nullable

### ISSUE THREAD

**Issue by acalabro** [SimonePaioletti/BPMNPathExtractor#2]
https://github.com/SimonePaioletti/BPMNPathExtractor/blob/4284e13e3512abcd711b26def42b94e2c0871dde/src/it/cnr/isti/labsedc/BPMNParser.java#L19

Why are you using '@Nullable' type?

**Comment by SimonePaioletti** [comment]
I read that is a good practice to annotate with '@nullable' all methods that can return null. If it is an error I will remove it.

**Comment by acalabro** [comment]
ok

**Comment by acalabro** [comment]
ok
