### ISSUE TITLE
Exception management

### ISSUE THREAD

**Issue by acalabro** [SimonePaioletti/BPMNPathExtractor#3]
https://github.com/SimonePaioletti/BPMNPathExtractor/blob/4284e13e3512abcd711b26def42b94e2c0871dde/src/it/cnr/isti/labsedc/BPMNParser.java#L28

It's strongly discouraged to use "Exception" in order to capture all the exception,
some information for localize the bug shouldn't be caught and however
you are calling a superclass instead of the specific one that can provide you 
more information about which of the object fails .

You should capture JUST the exception needed.

In this case: 
IOException
SAXException
ParserConfigurationException

You are in Java 8 so you can also use the multi try/multi-catch style.

**Comment by SimonePaioletti** [comment]
Done
