### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by acalabro** [SimonePaioletti/BPMNPathExtractor#5]
In order to make a self-contained project,
you can look at solution like maven 
in order to avoid missing libraries when you import
your project in an environment.

for example the library at row:

https://github.com/SimonePaioletti/BPMNPathExtractor/blob/24238adde0f56c86a6f2f9a49dd0d28b72e17b3c/src/it/cnr/isti/labsedc/bpmnpathextractor/BPMNParser.java#L9

is missing.. 
with maven this library will be downloaded automatically.

**Comment by SimonePaioletti** [comment]
I started to use Maven and I added that library to the dependencies. This is the first time that I use Maven so I hope that I did it properly.

**Comment by acalabro** [comment]
Maven works with goals,
you should enrich your pom with goal to launch within the ide or manually.
for example executing 
mvn install or mvn package in order to create a jar with dependencies.

**Comment by SimonePaioletti** [comment]
I extended my pom, now maven's plugins like install, package, compile and clean are supported
